import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Brain, CircleStop, MessageCircle, Mic, RotateCcw, Send, Volume2, Waves } from 'lucide-react';
import { motion } from 'framer-motion';
import { api } from '../lib/api';
import { Card, PageTitle } from '../components/UI';

type Step = 'setup' | 'explain' | 'feedback' | 'chat';

export default function FeynmanPage() {
  const [topic,setTopic]=useState(''), [text,setText]=useState(''), [interim,setInterim]=useState('');
  const [step,setStep]=useState<Step>('setup'), [listening,setListening]=useState(false), [error,setError]=useState('');
  const [language,setLanguage]=useState('en-US'), [elapsed,setElapsed]=useState(0), [feedback,setFeedback]=useState<any>(null), [busy,setBusy]=useState(false);
  const [chat,setChat]=useState<any[]>([]), [reply,setReply]=useState(''), [chatBusy,setChatBusy]=useState(false);
  const recognition=useRef<any>(null), base=useRef(''), started=useRef(0);
  const SR=typeof window!=='undefined'&&((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition);
  const words=text.trim()?text.trim().split(/\s+/).length:0;

  useEffect(()=>{if(!listening)return;const id=setInterval(()=>setElapsed(Math.floor((Date.now()-started.current)/1000)),1000);return()=>clearInterval(id)},[listening]);
  useEffect(()=>()=>{try{recognition.current?.stop()}catch{} speechSynthesis.cancel()},[]);

  function startVoice(){
    if(!SR)return setError('Live speech recognition is unavailable in this browser. Try Chrome or Edge.');
    setError('');base.current=text.trim();const r=new SR();recognition.current=r;r.continuous=true;r.interimResults=true;r.lang=language;
    r.onstart=()=>{started.current=Date.now();setElapsed(0);setListening(true)};
    r.onresult=(e:any)=>{let final='',live='';for(let i=e.resultIndex;i<e.results.length;i++){const phrase=e.results[i][0].transcript;e.results[i].isFinal?final+=phrase+' ':live+=phrase}if(final){const next=[base.current,final.trim()].filter(Boolean).join(' ');base.current=next;setText(next)}setInterim(live)};
    r.onerror=(e:any)=>{setError(e.error==='not-allowed'?'Allow microphone permission, then retry.':`Voice recognition stopped: ${e.error}`);setListening(false)};
    r.onend=()=>{setListening(false);setInterim('');recognition.current=null};
    try{r.start()}catch{setError('Microphone is already active.')}
  }
  function stopVoice(){try{recognition.current?.stop()}catch{}setListening(false);setInterim('')}
  async function analyze(){stopVoice();if(text.trim().length<20)return setError('Explain a little more for useful feedback.');setBusy(true);setError('');try{const result=await api<any>('feynman',{method:'POST',body:JSON.stringify({topic,explanation:text})});setFeedback(result);setChat([{role:'buddy',content:result.question}]);setStep('feedback');speechSynthesis.speak(new SpeechSynthesisUtterance(`You scored ${result.score} out of 100. ${result.encouragement}`))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function continueChat(e:React.FormEvent){e.preventDefault();if(!reply.trim()||chatBusy)return;const message=reply;setReply('');setChat(x=>[...x,{role:'user',content:message}]);setChatBusy(true);try{const result=await api<any>('feynman-chat',{method:'POST',body:JSON.stringify({topic,explanation:text,previousFeedback:feedback,userMessage:message})});setChat(x=>[...x,{role:'buddy',content:result.response}])}catch{setChat(x=>[...x,{role:'buddy',content:'I had trouble with that. Could you rephrase your answer?'}])}finally{setChatBusy(false)}}
  function reset(){stopVoice();speechSynthesis.cancel();setTopic('');setText('');setInterim('');setFeedback(null);setChat([]);setError('');setStep('setup')}

  return <>
    <PageTitle eyebrow="The Feynman technique, reimagined" title="Teach Buddy to learn it yourself" desc="Speak naturally. Buddy transcribes your explanation live, then finds gaps."/>
    <motion.section initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.45,ease:[.22,1,.36,1]}} className="mb-5 flex w-full items-start gap-4 rounded-2xl border border-white/10 bg-slate-950/70 p-5 shadow-xl shadow-violet-950/10 backdrop-blur-xl sm:p-6">
      <div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-cyan-400 text-white shadow-lg shadow-violet-500/20"><Brain size={21}/></div>
      <div><h2 className="text-lg font-semibold text-white">What is the Feynman Technique?</h2><p className="mt-1 text-sm leading-relaxed text-gray-400">The Feynman Technique is based on a simple idea: if you can teach a concept, you truly understand it. Instead of memorizing information, you explain a topic in your own words as if you're teaching a beginner. Any gaps, confusion, or oversimplifications reveal areas that need more attention. Buddy listens to your explanation, identifies those knowledge gaps, and helps you build a deeper, more complete understanding.</p></div>
    </motion.section>
    <div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]">
      <Card className="relative grid min-h-[460px] place-items-center overflow-hidden"><div className="absolute inset-0 bg-gradient-to-b from-violet-500/10 to-cyan-400/5"/><div className={`robot ${listening?'listening':''}`}><div className="antenna"><i/></div><div className="robot-head"><div className="eyes"><i/><i/></div><div className="mouth"/></div><div className="robot-body"><span>{listening?<Waves className="animate-pulse"/>:'AI'}</span></div></div><div className="relative text-center"><h3 className="text-xl font-bold">{step==='setup'?"Hi, I'm Buddy!":listening?'I can hear you…':step==='explain'?'Ready when you are!':'Let’s close the gaps!'}</h3><p className="mt-2 max-w-sm text-sm text-slate-500">{step==='setup'?'Teach me as if I’m a curious 10-year-old.':listening?`Recording ${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')}`:`We’re working on “${topic}”.`}</p>{listening&&<div className="mx-auto mt-4 flex w-fit items-center gap-1.5">{[1,2,3,4,5,6].map(i=><i key={i} className="voice-bar"/>)}</div>}</div></Card>
      <Card>
        {step==='setup'&&<div className="flex h-full flex-col justify-center"><span className="text-sm font-bold text-violet-500">STEP 1 OF 3</span><h2 className="mt-3 text-2xl font-bold">What will you teach Buddy?</h2><p className="mt-2 text-sm text-slate-500">Choose one concept for the clearest feedback.</p><input className="input mt-7" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. How gravity bends spacetime"/><div className="mt-4 flex flex-wrap gap-2">{['Photosynthesis','Supply & demand','Newton’s laws','Recursion'].map(x=><button key={x} onClick={()=>setTopic(x)} className="rounded-full bg-violet-500/10 px-3 py-2 text-xs text-violet-500">{x}</button>)}</div><button onClick={()=>topic.trim()&&setStep('explain')} disabled={!topic.trim()} className="btn-primary mt-7">Start teaching <Send size={17}/></button></div>}
        {step==='explain'&&<div><div className="flex items-center justify-between"><span className="text-sm font-bold text-violet-500">STEP 2 OF 3</span><select value={language} onChange={e=>setLanguage(e.target.value)} disabled={listening} className="rounded-xl border border-slate-300 bg-transparent px-3 py-2 text-xs dark:border-white/10"><option value="en-US">English</option><option value="hi-IN">Hindi</option><option value="es-ES">Spanish</option><option value="fr-FR">French</option></select></div><h2 className="mt-4 text-2xl font-bold">Explain it simply</h2>{error&&<p className="mt-4 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-500">{error}</p>}<div className={`relative mt-5 rounded-2xl ${listening?'ring-2 ring-cyan-400/50':''}`}><textarea value={text} onChange={e=>{setText(e.target.value);base.current=e.target.value}} className="input !mt-0 min-h-64 resize-none pb-12" placeholder="Your live transcript appears here…"/>{interim&&<p className="absolute bottom-12 left-4 text-sm italic text-cyan-500">{interim}…</p>}<span className="absolute bottom-3 left-4 text-xs text-slate-400">{words} words</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{listening?<button onClick={stopVoice} className="flex items-center justify-center gap-2 rounded-xl border border-rose-500 py-3 font-semibold text-rose-500"><CircleStop/>Stop & keep transcript</button>:<button onClick={startVoice} className="flex items-center justify-center gap-2 rounded-xl border border-cyan-500/40 py-3 font-semibold text-cyan-500"><Mic/>Explain by voice</button>}<button onClick={analyze} disabled={busy||words<4} className="btn-primary">{busy?'Analyzing…':'Analyze explanation'}</button></div></div>}
        {(step==='feedback'||step==='chat')&&feedback&&<div><div className="flex justify-between"><div><span className="text-sm font-bold text-violet-500">YOUR FEEDBACK</span><h2 className="mt-2 text-2xl font-bold">Understanding score</h2></div><div className="grid h-20 w-20 place-items-center rounded-full bg-violet-500/10 text-2xl font-bold text-violet-500">{feedback.score}</div></div><div className="mt-5 rounded-2xl bg-emerald-500/10 p-4"><b className="text-emerald-500">What you explained well</b><p className="mt-2 text-sm">{feedback.strength}</p></div><div className="mt-3 rounded-2xl bg-amber-500/10 p-4"><b className="text-amber-500">Buddy is still curious</b><p className="mt-2 text-sm">{feedback.question}</p></div><div className="mt-3 rounded-2xl bg-cyan-500/10 p-4"><b className="text-cyan-500">Try this next</b><p className="mt-2 text-sm">{feedback.suggestion}</p></div>{step==='feedback'?<div className="mt-5 flex gap-3"><button onClick={()=>setStep('chat')} className="btn-primary flex-1"><MessageCircle size={17}/>Continue conversation</button><button onClick={reset} className="glass rounded-xl p-3"><RotateCcw/></button></div>:<><div className="mt-5 max-h-64 space-y-3 overflow-y-auto rounded-2xl border border-white/10 p-4">{chat.map((m,i)=><div key={i} className={m.role==='user'?'text-right':''}><span className={`inline-block rounded-xl px-3 py-2 text-sm ${m.role==='user'?'bg-violet-600 text-white':'bg-white/5'}`}>{m.content}</span></div>)}{chatBusy&&<p className="animate-pulse text-xs text-slate-500">Buddy is thinking…</p>}</div><form onSubmit={continueChat} className="mt-3 flex gap-2"><input className="input !mt-0" value={reply} onChange={e=>setReply(e.target.value)} placeholder="Reply to Buddy…"/><button className="rounded-xl bg-violet-600 px-4 text-white"><ArrowRight/></button></form></>}</div>}
      </Card>
    </div>
  </>;
}
